################################################################################
# Server Configuration
################################################################################

# System log (Morgan) prod or dev
LOG: prod

# Enable cors (cross-origin resource sharing)
CORS: true

# JWT user password encryption key (AUTH)
TOKEN_SECRET: secret_token

# Flow Server
# ONE_FLOW_SERVER:
#   PROTOCOL: 'https'
#   HOST: '0.0.0.0'
#   POST: 2474

# JWT life time (days)
LIMIT_TOKEN:
  MIN: 14
  MAX: 30